FROM ubuntu:20.04

# Set up environment
ENV TZ=UTC
ENV AUTOVACUUM=on
ENV UPDATES=disabled
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get update \
 && apt-get install -y \
  apache2 \
  apache2-dev \
  apt-transport-https \
  autoconf \
  build-essential \
  bzip2 \
  ca-certificates \
  cmake \
  debhelper \
  devscripts \
  gdal-bin \
  git \
  libagg-dev \
  libboost-all-dev \
  libbz2-dev \
  libcairo2-dev \
  libcairomm-1.0-dev \
  libfreetype6-dev \
  libgdal-dev \
  libgd-perl \
  libgd-perl \
  libgeos++-dev \
  libgeos-dev \
  libgeotiff5 \
  libgeotiff-dev \
  libicu-dev \
  libipc-sharelite-perl \
  libipc-sharelite-perl \
  libjson-perl \
  libjson-perl \
  liblua5.1-0-dev \
  liblua5.2-dev \
  liblua5.3-dev \
  libmapnik3.0 \
  libmapnik-dev \
  libpng-dev \
  libpq-dev \
  libproj-dev \
  libprotobuf-c-dev \
  libtiff5-dev \
  libtool \
  libxml2-dev \
  lua5.1 \
  lua5.3 \
  mapnik-utils \
  munin \
  munin-node \
  parallel \
  postgis \
  postgresql \
  postgresql-12-postgis-3 \
  postgresql-contrib \
  protobuf-c-compiler \
  python3-bs4 \
  python3-gdal \
  python3-mapnik \
  python3-matplotlib \
  python3-numpy \
  python3-setuptools \
  sudo \
  tar \
  ttf-unifont \
  unifont \
  unzip \
  wget \
 && apt-get clean autoclean \
 && apt-get autoremove --yes \
 && rm -rf /var/lib/{apt,dpkg,cache,log}/

# Add user 'gis'
RUN useradd -u 1000 -s /bin/bash -d /home/gis -m -G root gis

# Build and install osmium
WORKDIR /usr/src
RUN mkdir osmium \
 && cd osmium \
 && git clone https://github.com/mapbox/protozero \
 && git clone https://github.com/osmcode/libosmium \
 && git clone https://github.com/osmcode/osmium-tool \
 && cd osmium-tool \
 && mkdir build \
 && cd build \
 && cmake .. \
 && cmake . \
 && make \
 && make install \
 && rm -rf /usr/src/osmium

# Build and install osm2pgsql
WORKDIR /usr/src
RUN git clone git://github.com/openstreetmap/osm2pgsql.git \
  && cd osm2pgsql \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install \
  && rm -rf /usr/src/osm2pgsql

# Build and install mod_tile
COPY mod_tile.conf /etc/apache2/conf-available/mod_tile.conf
RUN git clone -b switch2osm git://github.com/SomeoneElseOSM/mod_tile.git \
  && cd mod_tile \
  && ./autogen.sh \
  && ./configure \
  && make \
  && make install \
  && make install-mod_tile \
  && mkdir /var/lib/mod_tile \
  && a2enconf mod_tile \
  && rm -rf /usr/src/mod_tile

# Install phyghtmap
RUN wget http://katze.tfiu.de/projects/phyghtmap/phyghtmap_2.23.orig.tar.gz \
 && tar -xvzf phyghtmap_2.23.orig.tar.gz \
 && cd phyghtmap-2.23 \
 && python3 setup.py install

# Install Tirex v0.6.4
RUN git clone https://github.com/openstreetmap/tirex.git \
 && cd tirex \
 && git checkout v0.6.4 \
 && make install \
 && rm -rf /usr/src/tirex

# Install OpenTopoMap
RUN git clone https://github.com/der-stefan/OpenTopoMap.git \
 && cd OpenTopoMap/mapnik/tools/ \
 && cc -o saddledirection saddledirection.c -lm -lgdal \
 && cc -Wall -o isolation isolation.c -lgdal -lm -O2 \
 && ln -s /external-data/srtm_data /usr/src/OpenTopoMap/mapnik/dem \
 && mkdir /usr/src/OpenTopoMap/mapnik/data \
 && ln -s /external-data/simplified-water-polygons-split-3857 /usr/src/OpenTopoMap/mapnik/data/simplified-water-polygons-split-3857 \
 && ln -s /external-data/water-polygons-split-3857 /usr/src/OpenTopoMap/mapnik/data/water-polygons-split-3857

# Copy Renderer Configuration Files
RUN rm -rf /etc/tirex/renderer/mapserver* /etc/tirex/renderer/test* /etc/tirex/renderer/wms* /etc/tirex/renderer/tms* /etc/tirex/renderer/openseamap*
COPY osm*.conf /etc/tirex/renderer/mapnik/
COPY mapnik.conf /etc/tirex/renderer/mapnik.conf
COPY tirex.conf /etc/tirex/tirex.conf
COPY apache.conf /etc/apache2/sites-available/000-default.conf

# Configure Tirex Directories
RUN mkdir /var/run/tirex \
 && chown gis /var/run/tirex \
 && mkdir /var/lib/tirex \
 && chown gis /var/lib/tirex

COPY postgresql.conf /etc/postgresql/12/main/postgresql.conf

COPY opentopomap.xml /usr/src/OpenTopoMap/mapnik

COPY otm /otm
COPY entities.xml.inc /usr/src/OpenTopoMap/mapnik/inc/entities.xml.inc

RUN /otm/patch_styles.sh

CMD ["/otm/start.sh"]